title: Tang's Homepage
page-top-title: Cindy G. Tangi
top-section-bg-text: AEOL
home-subtitle: Dr. Cindy G. Tang&ensp;|&ensp;董冠妤
copyright-text: '&copy; Cindy G. Tang 2025-2029. All Rights Reserved.'
